# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Properties-Simple
version:      0.12
version_from: Simple.pm
installdirs:  site
requires:
    Config::Find:                  0.18
    Config::Properties:            0.59

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
